# Generated by Django 5.1.7 on 2025-04-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
