# Generated by Django 5.1.7 on 2025-04-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_currency_transaction_location_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='currency',
            field=models.CharField(default='USD', max_length=255),
        ),
    ]
