# Generated by Django 5.1.7 on 2025-04-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_setup',
            field=models.BooleanField(default=False),
        ),
    ]
