# Generated by Django 5.1.7 on 2025-05-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_complete_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_currencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='main_currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
